2024-12-29 00:00:00:INFO:Performing scheduled database backup.
2024-12-29 00:00:00:INFO:Deleting oldest backup /home/farrit/spoolman_data/backups/spoolman.db.5
2024-12-29 00:00:00:INFO:Backing up SQLite database to /home/farrit/spoolman_data/backups/spoolman.db
2024-12-29 00:00:00:INFO:Copied 1 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 2 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 3 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 4 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 5 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 6 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 7 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 8 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 9 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 10 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 11 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 12 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 13 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 14 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 15 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 16 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 17 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 18 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 19 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 20 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 21 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 22 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 23 of 24 pages.
2024-12-29 00:00:00:INFO:Copied 24 of 24 pages.
2024-12-29 00:00:00:INFO:Backup complete.
2024-12-29 00:50:25:INFO:Syncing external DB.
2024-12-29 00:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 00:50:25:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(seconds=3600)], <function _sync at 0x7f8f1fd760>, (), {}, 0, True, datetime.datetime(2024, 12, 25, 19, 50, 25, 38938), None, False, None, None)`!
Traceback (most recent call last):
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 173, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(url + "filaments.json"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 145, in _parse_filaments_from_bytes
    return ExternalFilamentsFile.parse_raw(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 1277, in parse_raw
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ExternalFilamentsFile
2996.finish
  Input should be 'matte' or 'glossy' [type=enum, input_value='wood', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/enum
2024-12-29 01:50:25:INFO:Syncing external DB.
2024-12-29 01:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 01:50:25:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(seconds=3600)], <function _sync at 0x7f8f1fd760>, (), {}, 0, True, datetime.datetime(2024, 12, 25, 19, 50, 25, 38938), None, False, None, None)`!
Traceback (most recent call last):
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 173, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(url + "filaments.json"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 145, in _parse_filaments_from_bytes
    return ExternalFilamentsFile.parse_raw(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 1277, in parse_raw
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ExternalFilamentsFile
2996.finish
  Input should be 'matte' or 'glossy' [type=enum, input_value='wood', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/enum
2024-12-29 02:50:25:INFO:Syncing external DB.
2024-12-29 02:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 02:50:25:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(seconds=3600)], <function _sync at 0x7f8f1fd760>, (), {}, 0, True, datetime.datetime(2024, 12, 25, 19, 50, 25, 38938), None, False, None, None)`!
Traceback (most recent call last):
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 173, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(url + "filaments.json"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 145, in _parse_filaments_from_bytes
    return ExternalFilamentsFile.parse_raw(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 1277, in parse_raw
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ExternalFilamentsFile
2996.finish
  Input should be 'matte' or 'glossy' [type=enum, input_value='wood', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/enum
2024-12-29 03:50:25:INFO:Syncing external DB.
2024-12-29 03:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 03:50:25:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(seconds=3600)], <function _sync at 0x7f8f1fd760>, (), {}, 0, True, datetime.datetime(2024, 12, 25, 19, 50, 25, 38938), None, False, None, None)`!
Traceback (most recent call last):
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 173, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(url + "filaments.json"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 145, in _parse_filaments_from_bytes
    return ExternalFilamentsFile.parse_raw(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 1277, in parse_raw
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ExternalFilamentsFile
2996.finish
  Input should be 'matte' or 'glossy' [type=enum, input_value='wood', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/enum
2024-12-29 04:50:25:INFO:Syncing external DB.
2024-12-29 04:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 04:50:25:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(seconds=3600)], <function _sync at 0x7f8f1fd760>, (), {}, 0, True, datetime.datetime(2024, 12, 25, 19, 50, 25, 38938), None, False, None, None)`!
Traceback (most recent call last):
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 173, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(url + "filaments.json"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 145, in _parse_filaments_from_bytes
    return ExternalFilamentsFile.parse_raw(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 1277, in parse_raw
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ExternalFilamentsFile
2996.finish
  Input should be 'matte' or 'glossy' [type=enum, input_value='wood', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/enum
2024-12-29 05:50:25:INFO:Syncing external DB.
2024-12-29 05:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 05:50:25:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(seconds=3600)], <function _sync at 0x7f8f1fd760>, (), {}, 0, True, datetime.datetime(2024, 12, 25, 19, 50, 25, 38938), None, False, None, None)`!
Traceback (most recent call last):
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 173, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(url + "filaments.json"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/spoolman/externaldb.py", line 145, in _parse_filaments_from_bytes
    return ExternalFilamentsFile.parse_raw(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 1277, in parse_raw
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrit/Spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ExternalFilamentsFile
2996.finish
  Input should be 'matte' or 'glossy' [type=enum, input_value='wood', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/enum
2024-12-29 06:50:25:INFO:Syncing external DB.
2024-12-29 06:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 06:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2024-12-29 06:50:26:INFO:External DB synced. Filaments: 4514, Materials: 29
2024-12-29 07:50:25:INFO:Syncing external DB.
2024-12-29 07:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 07:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2024-12-29 07:50:25:INFO:External DB synced. Filaments: 4514, Materials: 29
2024-12-29 08:50:25:INFO:Syncing external DB.
2024-12-29 08:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 08:50:25:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2024-12-29 08:50:25:INFO:External DB synced. Filaments: 4514, Materials: 29
